#!/usr/bin/env bash

set -u

# shellcheck source=/dev/null
{
  source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
  source "${SCRIPT_DIR}/../include/tfmake/store.sh"
}

file::exist_condition \
  "${DATA_DIR}/apply/Makefile" \
  "tfmake makefile --apply"

truncate -s 0 "${DATA_DIR}/apply/outputs/visited"

export TF_IN_AUTOMATION=true
make -i -f "${DATA_DIR}/apply/Makefile" 2> "${DATA_DIR}/apply/logs/signpost.log"

store::basepath "${DATA_DIR}/apply/store"

exit_code=0

if [[ -f "${DATA_DIR}/apply/outputs/visited" ]]; then
  nodes=$(cat "${DATA_DIR}/apply/outputs/visited")

  store::use visited
  for node in ${nodes}; do
    value=true

    grep -qE "make: \[.*${node}\] Error .+" "${DATA_DIR}/apply/logs/signpost.log"
    [[ $? -eq 0 ]] && value=false && exit_code=1

    kv::set "${node}" "${value}"
  done
fi

rm -f "${DATA_DIR}/apply/outputs/visited"

exit "${exit_code}"
