#!/usr/bin/env bash

set -u

# shellcheck source=/dev/null
{
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/util.sh"
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/store.sh"
}

function usage() {
  cat << EOF
Usage:
  tfmake cleanup [options]

  This command cleanup the data directory.

Options:
  -h, --help, help  Show this help output.
EOF
  exit
}

case "${1-}" in
-h|--help|help)
  usage
  ;;
?*)
  printf ">>> Unknown option: %s\n\n" "${1}"
  usage
  ;;
esac

rm -rf "${TFMAKE_DATA_DIR:?}/${TFMAKE_CONTEXT}"
