#!/usr/bin/env bash

set -u

# shellcheck source=/dev/null
{
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/util.sh"
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/store.sh"
}

function usage() {
  cat << EOF
Usage:
  tfmake config [options]

  This command modify tfmake configuration.

Options:
  -h, --help, help  Show this help output.
  --set             Set a tfmake configuration value.
  --get             Get a tfmake configuration value.
EOF
  exit
}

[[ $# -eq 0 ]] && usage

action=""
key=""
value=""

case "${1-}" in
  -h|--help|help)
    usage
    ;;
  --set)
    action="set"
    key="${2-}"
    value="${3-}"
    shift 2
    ;;
  --get)
    action="get"
    key="${2-}"
    shift
    ;;
  ?*)
    printf "Unknown option: %s\n\n" "${1}"
    usage
    ;;
esac

# set a config value
if [[ "${action}" == "set" ]]; then
  util::global_config_set "${key}" "${value}"
fi

# get a config value
if [[ "${action}" == "get" ]]; then
  util::global_config_get "${key}"
fi
