#!/usr/bin/env bash

set -u

# shellcheck source=/dev/null
{
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/util.sh"
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/store.sh"
}

function usage() {
  cat << EOF
Usage:
  tfmake context [options]

  This command is an alias for 'tfmake config' over the context value.

Options:
  -h, --help, help  Show this help output.
  plan              Set the context value as 'plan'.
  apply             Set the context value as 'apply'.
EOF
  exit
}

[[ $# -eq 0 ]] && util::global_config_get "context"

case "${1-}" in
  -h|--help|help)
    usage
    ;;
  plan|apply)
    util::global_config_set "context" "${1}"
    ;;
  ?*)
    printf ">>> Unknown option: %s\n\n" "${1}"
    usage
    ;;
esac
