#!/usr/bin/env bash

set -u

# shellcheck source=/dev/null
{
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/util.sh"
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/store.sh"
}

util::context

function usage() {
  cat << EOF
Usage:
  tfmake gh-pr-comment [options]

  This command add a comment to a GitHub pull request.

Options:
  -h, --help, help  Show this help output.
  --number          Pull request number.
  --dry-run         Output the comment or its fragments to stdout.
EOF
  exit
}

number=""
dry_run=false

case "${1-}" in
  -h|--help|help)
    usage
    ;;
  --number)
    number=${2-}
    shift
    ;;
  --dry-run)
    dry_run=true
    ;;
  ?*)
    printf "Unknown option: %s\n\n" "${1}"
    usage
    ;;
esac

function add_header() {
  local file="${1-}"

  cat >> "${file}" << EOF
<details>
  <summary>continuation...</summary>

${BACKTICKS}
EOF
}

function add_footer() {
  local file="${1-}"

  cat >> "${file}" << EOF

${BACKTICKS}
</details>
EOF
}

# validations
SUMMARY_FILE="${TFMAKE_DATA_DIR}/${TFMAKE_CONTEXT}/outputs/summary.md"
BREADCRUMBS_FILE="${TFMAKE_DATA_DIR}/${TFMAKE_CONTEXT}/outputs/breadcrumbs"
FRAGMENTS_FILE="${TFMAKE_DATA_DIR}/${TFMAKE_CONTEXT}/outputs/fragments"

# The max value is 65536, but some room is left (1024).
readonly MAX_COMMENT_SIZE="${MAX_COMMENT_SIZE:-"64512"}"

if [[ "${dry_run}" == "false" && -z "${number}" ]]; then
  printf "Missing '--number' option.\n"
  exit 1
fi

util::file_exist_condition \
  "${SUMMARY_FILE}" \
  "tfmake summary"

util::file_exist_condition \
  "${BREADCRUMBS_FILE}" \
  "tfmake summary"

# subcommand
util::log_info "[tfmake:gh-pr-comment] adding comments to PR from 'terraform ${TFMAKE_CONTEXT}' execution logs."

size=$(wc -c "${SUMMARY_FILE}" | awk '{print $1}')

if [[ ${size} -le ${MAX_COMMENT_SIZE} ]]; then
  if [[ "${dry_run}" == "true" ]]; then
    cat "${SUMMARY_FILE}"
  else
    gh pr comment "${number}" -F "${SUMMARY_FILE}"
  fi
else
  title=$(head -n 1 "${SUMMARY_FILE}")

  awk -f "${TFMAKE_SCRIPT_DIR}/../share/tfmake/fragments.awk" \
    "${BREADCRUMBS_FILE}" \
    "${MAX_COMMENT_SIZE}" \
    > "${FRAGMENTS_FILE}"

  count=1
  total=$(awk "END{print NR}" "${FRAGMENTS_FILE}")

  while IFS= read -r line; do
    offset=$(echo "${line}" | awk '{print $1}')
    size=$(echo "${line}" | awk '{print $2}')

    fragment_file="${TFMAKE_DATA_DIR}/${TFMAKE_CONTEXT}/outputs/fragment-${count}.md"
    truncate -s 0 "${fragment_file}"

    # set title for any fragment other than first
    if [[ ${count} -ne 1 ]]; then
      echo "${title} [${count}/${total}]" > "${fragment_file}"
    fi

    header=$(echo "${line}" | awk '{print $3}')
    if [[ "${header}" == "true" ]]; then
      add_header "${fragment_file}"
    fi

    tail -c "+${offset}" "${SUMMARY_FILE}" | head -c "${size}" >> "${fragment_file}"

    # first fragment, update the title
    if [[ ${count} -eq 1 ]]; then
      sed -i "" -e "s/${title}/${title} [${count}\/${total}]/" "${fragment_file}"
    fi

    footer=$(echo "${line}" | awk '{print $4}')
    if [[ "${footer}" == "true" ]]; then
      add_footer "${fragment_file}"
    fi

    if [[ "${dry_run}" == "true" ]]; then
      cat "${fragment_file}"
    else
      gh pr comment "${number}" -F "${fragment_file}"
    fi

    ((count=count+1))
  done <  <(cat "${FRAGMENTS_FILE}")
fi
