#!/usr/bin/env bash

set -u

# shellcheck source=/dev/null
{
  source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
  source "${SCRIPT_DIR}/../include/tfmake/store.sh"
}

function usage() {
  cat << EOF
Usage:
  tfmake gh-step-summary [options]

  This command add content to GitHub Step Summary.

Options:
  -h, --help        Show this help output.
  --plan            Use the outputs from 'tfmake summary --plan'.
  --apply           Use the outputs from 'tfmake summary --apply'.
EOF
  exit
}

target=""
option="${1-}"
shift

case "${option}" in
-h|--help)
  usage
  ;;
--plan|--apply)
  target="${option:2}"
  ;;
*)
  usage
  ;;
esac

GITHUB_STEP_SUMMARY=${GITHUB_STEP_SUMMARY:-"/dev/null"}
cat "${DATA_DIR}/${target}/outputs/summary.md" >> "${GITHUB_STEP_SUMMARY}"
