#!/usr/bin/env bash

set -u

# shellcheck source=/dev/null
{
  source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
  source "${SCRIPT_DIR}/../include/tfmake/store.sh"
}

function usage() {
  cat << EOF
Usage:
  tfmake gh-step-summary [options]

  This command add content to GitHub Step Summary.

Options:
  -h, --help, help  Show this help output.
EOF
  exit
}

case "${1-}" in
-h|--help|help)
  usage
  ;;
?*)
  printf ">>> Unknown option: %s\n\n" "${1}"
  usage
  ;;
esac

GITHUB_STEP_SUMMARY=${GITHUB_STEP_SUMMARY:-"/dev/null"}
cat "${DATA_DIR}/${TFMAKE_CONTEXT}/outputs/summary.md" >> "${GITHUB_STEP_SUMMARY}"
