#!/usr/bin/env bash

set -u

# shellcheck source=/dev/null
{
  source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
  source "${SCRIPT_DIR}/../include/tfmake/store.sh"
}

function usage() {
  cat << EOF
Usage:
  tfmake init [options]

  This command initialize the data directory for Terraform plan/apply execution.

Options:
  -h, --help, help  Show this help output.
EOF
  exit
}

case "${1-}" in
-h|--help|help)
  usage
  ;;
?*)
  printf ">>> Unknown option: %s\n\n" "${1}"
  usage
  ;;
esac

mkdir -p "${DATA_DIR}/${TFMAKE_CONTEXT}/logs"
mkdir -p "${DATA_DIR}/${TFMAKE_CONTEXT}/outputs"

store::basepath "${DATA_DIR}/${TFMAKE_CONTEXT}/store"

store::use modules
while IFS= read -r -d '' file; do
  kv::set "$(dirname "${file}")" true
done <  <(find -- * -name main.tf -type f -print0)

store::use dependencies
while IFS= read -r -d '' file; do
  module=$(dirname "${file}")

  deps=$(yq -o=csv ".dependencies" "${file}")
  if [[ -n ${deps} ]]; then
    kv::set "${module}" "${deps}"
  fi
done <  <(find -- * -name .tfmake -type f -print0)
