#!/usr/bin/env bash

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
source "${SCRIPT_DIR}/../include/tfmake/store.sh"

file::exist_condition  \
  "${DATA_DIR}/apply/store/dependencies/keys" \
  "tfmake init --apply"

store::basepath "${DATA_DIR}/apply/store"

modules=$(kv::keys modules)

cat > "${DATA_DIR}/apply/Makefile" << EOF
all: $(utils::splitlines "${modules}")
EOF

for module in ${modules}; do
  deps=$(kv::get dependencies "${module}")
  [[ -n ${deps} ]] && deps=${deps//,/ }

  file::new_line "${DATA_DIR}/apply/Makefile"

  cat >> "${DATA_DIR}/apply/Makefile" << EOF
${module}: \$(wildcard ${module}/*.tf) ${deps}
${TAB}@mkdir -p "${DATA_DIR}/apply/logs/${module}"
${TAB}@echo "${module}" >> "${DATA_DIR}/apply/outputs/visited"
${TAB}terraform -chdir="${module}" init -no-color 2>&1 | tee -a "${DATA_DIR}/apply/logs/${module}/init.log"
${TAB}terraform -chdir="${module}" apply -auto-approve -no-color 2>&1 | tee -a "${DATA_DIR}/apply/logs/${module}/apply.log"
EOF
done
