#!/usr/bin/env bash

function usage() {
  cat << EOF
Usage:
  tfmake makefile [options]

  This command generate a Makefile for Terraform plan or apply execution.

Options:
  -h, --help        Show this help output.
  --plan            Generate a Makefile for 'terraform plan' execution.
  --apply           Generate a Makefile for 'terraform apply' execution.
EOF
  exit
}

usage
