#!/usr/bin/env bash

set -u

tab=$(printf '\t')

# shellcheck source=/dev/null
{
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/util.sh"
  source "${TFMAKE_SCRIPT_DIR}/../include/tfmake/store.sh"
}

store::basepath "${TFMAKE_DATA_DIR}/plan/store"

store::use modules
modules=$(kv::keys)

cat > "${TFMAKE_DATA_DIR}/plan/Makefile" << EOF
SHELL=$(which bash) -o pipefail
export TF_IN_AUTOMATION=true

include ${TFMAKE_DATA_DIR}/plan/recipes/grouping.mk

all: $(util::splitlines "${modules}")
EOF

store::use dependencies
for module in ${modules}; do
  deps=$(kv::get "${module}")
  [[ -n ${deps} ]] && deps=${deps//,/ }

  util::append_new_line "${TFMAKE_DATA_DIR}/plan/Makefile"

  cat >> "${TFMAKE_DATA_DIR}/plan/Makefile" << EOF
${module}: \$(wildcard ${module}/*.tf ${module}/*.tfvars) ${deps}
${tab}@mkdir -p "${TFMAKE_DATA_DIR}/plan/logs/${module}"
${tab}@echo "${module}" >> "${TFMAKE_DATA_DIR}/plan/outputs/visited"
${tab}@\$(call group,${module})
${tab}@terraform -chdir="${module}" init -no-color 2>&1 | tee "${TFMAKE_DATA_DIR}/plan/logs/${module}/init.log"
${tab}@terraform -chdir="${module}" plan -no-color 2>&1 | tee "${TFMAKE_DATA_DIR}/plan/logs/${module}/plan.log"
${tab}@\$(endgroup)
EOF
done
