#!/usr/bin/env bash

declare -A modules=()

mkdir -p "${DATA_DIR}/outputs/apply"
mkdir -p "${DATA_DIR}/makefiles/apply"

while IFS= read -r -d '' file; do
    module=$(dirname "${file}")
    modules["${module}"]=""

    echo "${module}" >> "${DATA_DIR}/outputs/apply/nodes"
done <  <(find -- * -name main.tf -type f -print0)

while IFS= read -r -d '' file; do
    module=$(dirname "${file}")
    modules["${module}"]=$(yq -o=tsv ".dependencies" "${file}")
done <  <(find -- * -name .tfmake -type f -print0)

echo "all:" "${!modules[@]}" > "${DATA_DIR}/makefiles/apply/Makefile"

for module in "${!modules[@]}"; do
    cat >> "${DATA_DIR}/makefiles/apply/Makefile" << EOF

${module}: ${modules[${module}]} \$(wildcard ${module}/*.tf)
	@mkdir -p "${DATA_DIR}/logs/apply/${module}"
	@echo "${module}" >> "${DATA_DIR}/outputs/apply/visited"

	terraform -chdir="${module}" init -no-color 2>&1 | tee -a "${DATA_DIR}/logs/apply/${module}/init.log"
	terraform -chdir="${module}" apply -auto-approve -no-color 2>&1 | tee -a "${DATA_DIR}/logs/apply/${module}/apply.log"
EOF
done
