#!/usr/bin/env bash

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
source "${SCRIPT_DIR}/../include/tfmake/store.sh"

file::exist_condition \
  "${DATA_DIR}/plan/store/dependencies/keys" \
  "tfmake init --plan"

store::basepath "${DATA_DIR}/plan/store"

modules=$(kv::keys modules)

cat > "${DATA_DIR}/plan/Makefile" << EOF
SHELL=$(which bash) -o pipefail

all: $(utils::splitlines "${modules}")
EOF

for module in ${modules}; do
  deps=$(kv::get dependencies "${module}")
  [[ -n ${deps} ]] && deps=${deps//,/ }

  file::new_line "${DATA_DIR}/plan/Makefile"

  cat >> "${DATA_DIR}/plan/Makefile" << EOF
${module}: \$(wildcard ${module}/*.tf ${module}/*.tfvars) ${deps}
${TAB}@mkdir -p "${DATA_DIR}/plan/logs/${module}"
${TAB}@echo "${module}" >> "${DATA_DIR}/plan/outputs/visited"
${TAB}terraform -chdir="${module}" init -no-color 2>&1 | tee "${DATA_DIR}/plan/logs/${module}/init.log"
${TAB}terraform -chdir="${module}" plan -no-color 2>&1 | tee "${DATA_DIR}/plan/logs/${module}/plan.log"
EOF
done
