#!/usr/bin/env bash

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
source "${SCRIPT_DIR}/../include/tfmake/store.sh"

file::exist_condition  \
  "${DATA_DIR}/plan/Makefile" \
  "tfmake makefile --plan"

truncate -s 0 "${DATA_DIR}/plan/outputs/visited"

export TF_IN_AUTOMATION=true
make -f "${DATA_DIR}/plan/Makefile"

store::basepath "${DATA_DIR}/plan/store"
store::kv visited

if [[ -f "${DATA_DIR}/plan/outputs/visited" ]]; then
  nodes=$(cat "${DATA_DIR}/plan/outputs/visited")
  for node in ${nodes}; do
    kv::set "${node}" true
  done
fi

rm -f "${DATA_DIR}/plan/outputs/visited"
