#!/usr/bin/env bash

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
source "${SCRIPT_DIR}/../include/tfmake/store.sh"

BACKTICKS='```'
MERMAID_FILE="${DATA_DIR}/plan/outputs/mermaid.md"
SUMMARY_FILE="${DATA_DIR}/plan/outputs/summary.md"

file::exist_condition  \
  "${MERMAID_FILE}" \
  "tfmake mermaid --plan"

truncate -s 0 "${SUMMARY_FILE}"

# mermaid
cat >> "${SUMMARY_FILE}" << EOF
${BACKTICKS}mermaid
$(cat "${MERMAID_FILE}")
${BACKTICKS}
EOF

file::new_line "${SUMMARY_FILE}"

# logs
store::basepath "${DATA_DIR}/plan/store"
nodes=$(kv::keys visited)

for node in ${nodes}; do
  cat >> "${SUMMARY_FILE}" << EOF
<details>
<summary>Module <strong>"${node}"</strong> Plan</summary>

${BACKTICKS}
$(cat "${DATA_DIR}/plan/logs/${node}/init.log")
${BACKTICKS}

${BACKTICKS}
$(cat "${DATA_DIR}/plan/logs/${node}/plan.log")
${BACKTICKS}

</details>
EOF
done
