#!/usr/bin/env bash

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../include/tfmake/utils.sh"
source "${SCRIPT_DIR}/../include/tfmake/store.sh"

BACKTICKS='```'
MERMAID_FILE="${DATA_DIR}/apply/outputs/mermaid.md"
SUMMARY_FILE="${DATA_DIR}/apply/outputs/summary.md"
SUMMARY_TITLE="${SUMMARY_TITLE:-""}"

file::exist_condition \
  "${MERMAID_FILE}" \
  "tfmake mermaid --apply"

truncate -s 0 "${SUMMARY_FILE}"

# title
if [[ -n "${SUMMARY_TITLE}" ]]; then
  echo "### ${SUMMARY_TITLE}" > "${SUMMARY_FILE}"
fi

file::new_line "${SUMMARY_FILE}"

# mermaid
cat >> "${SUMMARY_FILE}" << EOF
${BACKTICKS}mermaid
$(cat "${MERMAID_FILE}")
${BACKTICKS}
EOF

file::new_line "${SUMMARY_FILE}"

# logs
store::basepath "${DATA_DIR}/apply/store"
nodes=$(kv::keys visited)

for node in ${nodes}; do
  cat >> "${SUMMARY_FILE}" << EOF
<details>
<summary>Module <strong>"${node}"</strong> Apply</summary>

${BACKTICKS}
$(cat "${DATA_DIR}/apply/logs/${node}/init.log")

--------------------------------------------------------------------------------

$(cat "${DATA_DIR}/apply/logs/${node}/apply.log")
${BACKTICKS}

</details>
EOF
done
