#!/usr/bin/env bash

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/../include/tfmake/utils.sh"

function usage() {
  cat << EOF
Usage:
  tfmake summary [options]

  This command create a Markdown summary.

Options:
  --help            Show this help output.
  --plan            Use Mermaid diagram and outputs from 'tfmake plan'.
  --apply           Use Mermaid diagram and outputs from 'tfmake apply'.
EOF
  exit
}

usage
