#!/usr/bin/env bash

readonly BACKTICKS='```'
readonly SUMMARY="${WORKDIR}/outputs/apply/summary.md"

if [[ ! -f "${WORKDIR}/outputs/apply/mermaid.md" ]]; then
    cat << EOF
Error: file "${WORKDIR}/outputs/apply/mermaid.md" does not exist.

>>> Run 'tfmake mermaid --apply' first."
EOF
    exit 1
fi

truncate -s 0 "${SUMMARY}"

# mermaid
cat >> "${SUMMARY}" << EOF
${BACKTICKS}mermaid
$(cat "${WORKDIR}/outputs/apply/mermaid.md")
${BACKTICKS}
EOF

# init and apply logs
if [[ -f ${WORKDIR}/outputs/apply/visited ]]; then
    nodes=$(cat "${WORKDIR}/outputs/apply/visited")

    for node in ${nodes}; do
        cat >> "${SUMMARY}" << EOF
<details>
<summary>Module <strong>"${node}"</strong> Apply</summary>

${BACKTICKS}
$(cat "${WORKDIR}/logs/apply/${node}/init.log")
${BACKTICKS}

${BACKTICKS}
$(cat "${WORKDIR}/logs/apply/${node}/apply.log")
${BACKTICKS}

</details>	
EOF
    done
fi
